### ISSUE TITLE
Can't load post or comments on frontpage

### ISSUE THREAD

**Issue by radeonxray** [edipetres/HackerNews-GroupF#22]
Frontpage fails to load both post and comments

Upon opening the (Live) Frontpage, this alert pops up, along with the following console-warning.

https://ibb.co/iZDvSf

This also goes for when trying to reload the comments, when clicking on the "Comments"-option

https://ibb.co/c0ALtL

**Comment by Nexao** [comment]
Closed in 06913981e56672572370b803a77a96b2763ed710
Closed in 6f9ebafe76e7999084fae50425e4ba2590161e83
