### ISSUE TITLE
Can't create post or comments [Frontend]

### ISSUE THREAD

**Issue by radeonxray** [edipetres/HackerNews-GroupF#24]
Can't create new post or comments through the frontend, either as a user or anonymously.
Will acknowledge that the server is handling Helge's incoming data correctly.

**Comment by Ekskursantas** [comment]
4043d3c2b28764ee40868920e1034589038ce825 - For creating comments
d2a902b6472b0416aa66de074bd47900f42a90a2 - For creating posts
