### ISSUE TITLE
Frontend: Create new User feedback suggestion

### ISSUE THREAD

**Issue by radeonxray** [edipetres/HackerNews-GroupF#35]
Just tested the create new user, works fine so far. I know the commit stated that there is currently no feedback when creating the user (only in the inspector).

As a temp. fix, might we suggest using a simple alert();?

Might also want to disable the "create user"-button, unless there is content in username and password, and perhaps even return an alert with a warning (and failed creating user), if the username and password is not long enough.

**Comment by edipetres** [comment]
Thanks for the feedback and suggestions - will implement creating a user today with @Nexao. In the meantime feel free to use any user from `/utils/users_short.csv`

**Comment by radeonxray** [comment]
https://github.com/edipetres/HackerNews-GroupF/commit/2fcb4525ee3d62ddfd41c0d10cc7420d2fac07c9
