### ISSUE TITLE
Frontend: Login Status Feedback

### ISSUE THREAD

**Issue by radeonxray** [edipetres/HackerNews-GroupF#36]
Login seems to work perfectly! It took me straight to the frontpage afterwards

When logged in however, the upper right text still says "Login".

Maybe change it to "Logout(Username)" when logged in.

Also, the login data (username, password, JWT-token) is currently being exposed in the inspector when loggin-in.

**Comment by radeonxray** [comment]
https://github.com/edipetres/HackerNews-GroupF/commit/898397f0ea2df3f48ee657504edb5b0f6778591e

**Comment by Nexao** [comment]
When logged in it no longer shows the login button, instead you see your username and a logout button
