### ISSUE TITLE
Frontend: Create new user that already exist

### ISSUE THREAD

**Issue by radeonxray** [edipetres/HackerNews-GroupF#37]
So the system (correctly) denied me creating a user with the same username (with the same/different password also), but only told me that through the inspector.

Please give some kind of feedback, even if just for a temp. solution like was sugested here:
https://github.com/edipetres/HackerNews-GroupF/issues/35

**Comment by Nexao** [comment]
Closed in 528fb169dfaf81f4b794fd410a96a4b4533f0856
