### ISSUE TITLE
Story reference in the comment json

### ISSUE THREAD

**Issue by Ekskursantas** [edipetres/HackerNews-GroupF#40]
Can we add a story/article id to the comment json for the new comments and also maybe the title. Because right now in the new comments the only things that I can get is the comments id and it's parents which may be another comment or the story. So, if we had the stories id inside the comment and the title name. I could visually display the title in the new comments and redirect to the story when clicked on it. Right now if the comment is the child of the story it will then show the story correctly in the page otherwise it will throw an exception because properties do not exist on comment that exist on the story.

**Comment by edipetres** [comment]
closed in 68581de
