### ISSUE TITLE
Frontend-Submit: Submit-option when not logged in?

### ISSUE THREAD

**Issue by radeonxray** [edipetres/HackerNews-GroupF#42]
Even if not logged in, the Submit option is available from the navar, despite the fact that one cannot post new stories without being logged-in. 
Perhaps this option should be hidden from the navbar and only shown if one is logged in?

**Comment by Ekskursantas** [comment]
In original hacker news the button just redirects to the login page, if not logged in and that is what we did in #41 a677d4cfac52b62f74973d8205cf0902c2f5f540
