### ISSUE TITLE
Frontend-MainScreen: Missing Voting feedback

### ISSUE THREAD

**Issue by radeonxray** [edipetres/HackerNews-GroupF#50]
- No feedback is really given when voting on a story, besides the arrow disappearing.
- If voting on a story, but not logged in, no feedback is given. Only within inspector can one see that something went wrong and the request was denied.

**Comment by Ekskursantas** [comment]
The feedback for the voting if not logged in is resolved in the commit that will close this issue. The voting when logged in however does not give any feedback even on the original hackernews page, you can only see the upvote only after the page was refreshed. (Though still need to work on the voting)

**Comment by Ekskursantas** [comment]
17530eb7c284e366ef51790a2305aa8885675620
