### ISSUE TITLE
Create login/registration page

### ISSUE THREAD

**Issue by edipetres** [edipetres/HackerNews-GroupF#6]
This page should be accessible from `domain.com/auth`, you have to use vue router to serve this page on the given url.

Use the following design:
![image](https://user-images.githubusercontent.com/17946439/46407641-e548f200-c70f-11e8-8f4a-8232f580730a.png)

Add API call in the Vue component for signup and login API and handle responses.

For login, send `username` and `password` fields to the backend for verification.
For registration, send the same fields for the register API endpoint.
Consult the API protocol (find the API documentation on the root of the project) to find the particular endpoints.

**Comment by Nexao** [comment]
The login creating has finished
