### ISSUE TITLE
Comment on a Post FRONTEND

### ISSUE THREAD

**Issue by DarkSideMatters** [edipetres/HackerNews-GroupF#8]
User must be able to comment on a post. The comment will be below the post in the same panel.

The comment must show userName, have a timestamp, vote points as shown below. 
![image](https://user-images.githubusercontent.com/17946439/46408248-c9465000-c711-11e8-8ca6-93ee86fa8699.png)

**Comment by Ekskursantas** [comment]
4043d3c2b28764ee40868920e1034589038ce825
